# NextCLoud with MariaDB/MySQL all behind Nginx acting as a Reverse Proxy with SSL Encryption from LetsEcrypt.
#
# During initial NextCLoud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: nextcloud 
# Database password: nextcloud
# Database name: nextcloud
# Database host: replace "localhost" with "db" the same name as the data base container name.
#

version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    restart: always

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:rw
    restart: always

  web:
    image: nginx
    container_name: nextcloud_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=cloud.kolgrov.net
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cloud.kolgrov.net
      - LETSENCRYPT_EMAIL=frodekolgrov@gmail.com
    networks:
      - proxy-tier
    restart: always

  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    networks:
      - proxy-tier
    restart: always
    
  db:
    image: mariadb
    container_name: db
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Ioxqoh86mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Ioxqoh86mariadb
    networks:
      - proxy-tier
    restart: always

  db_wp:
    image: mariadb
    container_name: db_wp
    volumes:
      - db_wp_data:/var/lib/mysql2
    environment:
      - MYSQL_ROOT_PASSWORD=Ioxqoh86wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=Ioxqoh86wordpress
    networks:
      - proxy-tier
    restart: always

  wordpress:
    depends_on:
      - db_wp
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      - VIRTUAL_HOST=home.kolgrov.net, kolgrov.net
      - LETSENCRYPT_HOST=home.kolgrov.net, kolgrov.net
      - LETSENCRYPT_EMAIL=frodekolgrov@gmail.com
      - WORDPRESS_DB_HOST=db_wp
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=Ioxqoh86wordpress
    networks:
      - proxy-tier

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=docker.kolgrov.net
      - VIRTUAL_PORT=9000
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=docker.kolgrov.net
      - LETSENCRYPT_EMAIL=frodekolgrov@gmail.com
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy

volumes:
  portainer_data:
  db_wp_data:
